### ISSUE TITLE
Add Intellivision Demon Debugger source code

### ISSUE THREAD

**Issue by intvnut** [palazzol/demon#1]
Frank,

Does it make sense for me to push an update here that includes the Demon Debugger back-end source code for the Intellivision?  I have no issue sharing it with the world.

Do you have a preferred license?  I'm OK w/ CC0 Public Domain for my Intellivision code.

--J

**Comment by palazzol** [comment]
Well, 3+ years later, I say yes!  I am working on version 2,0 of this stuff now, and I'd love to include that.  CC0 Public Domain is fine.

**Comment by palazzol** [comment]
Committed code - closing issue
