### ISSUE TITLE
Ribbon to PDIP 24 connector

### ISSUE THREAD

**Issue by srwalter** [palazzol/demon#3]
What's the part number for the ribbon cable to PDIP-24 adapter?  What would you even call that?

Nice talk at VCFMW, by the way

**Comment by abzman** [comment]
I used this for one end of the cable: https://www.lcsc.com/product-detail/IDC-Connectors_JILN-531424YBS0BW01_C601916.html

As for the cable it's just a strip of 24 pin ribbon, technically it's 0.05" pitch, but in reality it's just a bit of ide or floppy ribbon cable that's been peeled back to 24 pins.  

Frank sourced the ribbon to dip parts I think.

**Comment by palazzol** [comment]
Going back through my order history, looks like it was this part from Mouser:
[https://www.mouser.com/ProductDetail/629-CWR-130-24-0000](https://www.mouser.com/ProductDetail/629-CWR-130-24-0000)

**Comment by srwalter** [comment]
Thanks!
